version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    environment:
      POSTGRES_HOST: app-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      BASEURL: http://localhost:5000/
      DOCKER_HOST: app:80
      FLASK_APP_INSTANCE: /app/instance
      FLASK_APP: /app/app
      FLASK_APP_MIGRATIONS: /app/migrate/migrations
    volumes:
      - ./migrate:/app/migrate
    ports:
      - "5000:80"
    depends_on:
      - app-db
      - zoo1
      - zoo2
      - zoo3

  # https://hub.docker.com/_/postgres
  app-db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - app-data:/var/lib/postgresql/

  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    
  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    
  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888

volumes:
  app-data:
