version: '3.7'

services:
  app-logic:
    build: .
    ports:
    - "5000:5000"

  # https://hub.docker.com/_/postgres
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
